name: Build & Upload Site

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Setup Environment.
      run: |
        cd site
        gem install jekyll bundler
        bundle install
        sudo apt-get install -y ncftp

    - name: Build Site with Jekyll.
      run: |
        cd site
        JEKYLL_ENV=production bundle exec jekyll build

    - name: Deploy with Rsync.
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: site/_site/
        remote_path: domains/kylebatson.com/html
        remote_host: ${{ secrets.FTP_LOCATION }}
        remote_user: ${{ secrets.FTP_USERNAME }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
